name: RECORDER

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
          
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
             python-version: '3.10'
             
        - name: Print date and time
          run: echo "Workflow started at $(TZ='Asia/Ho_Chi_Minh' date)"
          
        - name: Install dependencies
          run: pip install -r src/requirements.txt
  
        - name: Update and upgrade packages
          run: sudo apt-get update && sudo apt-get upgrade -y
        
        - name: Install FFmpeg
          run: sudo apt-get install -y ffmpeg
  
        - name: Create user folders
          run: mkdir -p $GITHUB_WORKSPACE/VIDEOS

        - name: Install OpenVPN and Connect to VPN
          run:  |
              sudo apt install -y openvpn openvpn-systemd-resolved
              
        - name: Connect to VPN
          uses: "kota65535/github-openvpn-connect-action@v2"
          with:
            config_file: newuser.ovpn
  
        - name: Run Selenium script
          run: python src/main.py -user vuson389 -output VIDEOS
        - name: Archive screenshots
          uses: actions/upload-artifact@v4
          if: always()
          with:
            name: vuson389
            path: VIDEOS
