name: RDB_msstore

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Create Windows User
      run: New-LocalUser -Name "newuser" -Password (ConvertTo-SecureString "Duythanh123." -AsPlainText -Force) -FullName "New User" -Description "Description of New User" -AccountNeverExpires

    - name: Grant Admin Rights
      run: Add-LocalGroupMember -Group "Administrators" -Member "newuser"

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # - name: Install dependencies
    #   run: |
    #     pip install PyAutoGUI opencv-python

    - name: Enable RDP User Authentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    # ⚙️ Cài ngrok từ Microsoft Store thay vì tải từ bin.equinox.io
    - name: Install ngrok from Microsoft Store
      run: winget install ngrok.ngrok -s msstore --accept-source-agreements --accept-package-agreements

    - name: Auth
      run: ngrok config add-authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Create Tunnel
      run: ngrok tcp 3389
